[package]
name = "wayhub"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
directories = "5.0.1"
octocrab = "0.41.2"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = "1.41.0"
toml = "0.8.19"
